// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb-BX5XVcD_N6ksP1hMs5fOYaLCShpRWI',
    appId: '1:850065446996:web:b2f50a61363a8520de75c1',
    messagingSenderId: '850065446996',
    projectId: 'dataofice-f0305',
    authDomain: 'dataofice-f0305.firebaseapp.com',
    storageBucket: 'dataofice-f0305.appspot.com',
    measurementId: 'G-RCE5XK0QYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbYYLLWfAi-ee_FMSmfOoeKbjKtxsqr-Y',
    appId: '1:850065446996:android:d3aac1e0f23107f3de75c1',
    messagingSenderId: '850065446996',
    projectId: 'dataofice-f0305',
    storageBucket: 'dataofice-f0305.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9VfgyvK94H0VtuidIJh-mEKKeFc0dvD4',
    appId: '1:850065446996:ios:95c7b2635251ef30de75c1',
    messagingSenderId: '850065446996',
    projectId: 'dataofice-f0305',
    storageBucket: 'dataofice-f0305.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9VfgyvK94H0VtuidIJh-mEKKeFc0dvD4',
    appId: '1:850065446996:ios:f0ca3f8d695951a7de75c1',
    messagingSenderId: '850065446996',
    projectId: 'dataofice-f0305',
    storageBucket: 'dataofice-f0305.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
